baseline: Your blogging assistant.
theme: hyde
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ""
keywords: Cecil, Static Site Generator, SSG
author: Arnaud Ligny
title: Yazid Blog
description: A ready to use static blog, powered by Cecil.
baseurl: /
canonicalurl: true
date:
  format: j F Y
  timezone: Europe/London
virtualpages:
  - path: admin
    title: Content Manager (Netlify CMS)
    layout: admin/index
    output: html
  - path: _redirects
    output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
postprocess:
  enabled: true
